# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATYCU8xhagrfNvPTGft_dJGZ8YutPIsh
"""

list1 = ["mac","dell","hp","lenovo"]               #list 1 in ascending order
sorted(list1)

list2 = ["nike","reebok","teamspirit","uspolo"]    #list 2 in ascending order
sorted(list2)

list3 = []
list3.append(sorted(list1) +sorted(list2))        #overlapping both lists

print(list3)                                      #sorted the overlapping list

range_numbers = range(20,40,2)                    #range  with numbers
print(range_numbers)

for i in range(20,40,2):                           #even numbers print 
  print(i,end="$")

